sudo: required
services:
  - docker

before_install:
  - docker build -t propoudel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true propoudel/react-test npm test

after_success:
  - docker build -t propoudel/multi-client ./client
  - docker build -t propoudel/multi-nginx ./nginx
  - docker build -t propoudel/multi-server ./server
  - docker build -t propoudel/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push propoudel/multi-client
  - docker push propoudel/multi-nginx
  - docker push propoudel/multi-server
  - docker push propoudel/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-1-077134674091"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
